baseURL: "https://hugo-theme-shoka.birdgg.me/"
languageCode: "en-us"
defaultContentLanguage: zh-cn
title: title
theme: "hugo-theme-shoka"

author:
  name: birdgg

enableEmoji: true

hasCJKLanguage: true
summaryLength: 50

paginate: 8
taxonomies:
  tag: tags
  series: series

permalinks:
  posts: /:slug
  tags: /tags/:slug/

markup:
  highlight:
    style: 'doom-one2'
    guessSyntax: true
    lineNumbersInTable: false
    lineNos: true
    codeFences: true
    tabWidth: 2
    noClasses: false
  goldmark:
    renderer:
      unsafe: true # enable html in markdown
  tableOfContents:
    endLevel: 2
    ordered: true
    startLevel: 2

menu:
  main:
  - identifier: home
    name: 首页
    params: 
      icon: ic i-home
    weight: 10
    url: /
  - identifier: articles
    name: 文章
    params: 
      icon: ic i-feather
    weight: 40
  - identifier: archives
    name: 归档
    params:
      icon: ic i-list-alt
    url: /archives/
    parent: articles
    weight: 1
  - identifier: categories
    name: 分类
    params:
      icon: ic i-th
    url: /categories/
    parent: articles
    weight: 2
  - identifier: tags
    name: 标签
    params:
      icon: ic i-tags
    url: /tags/
    parent: articles
    weight: 3
  - identifier: about
    name: 关于
    params:
      icon: ic i-user
    url: /about
  - identifier: links
    name: 链环
    params:
      icon: ic i-magic
  - identifier: friends
    name: 友链
    params:
      icon: ic i-heart
    url: /friends/
    parent: links
  - identifier: websites
    name: 网址
    params:
      icon: ic i-star
    url: /webstack/
    parent: links

outputs:
  home: ["HTML", "RSS", "JSON", "Algolia"]

outputFormats:
  Algolia:
    baseName: algolia
    isPlainText: true
    mediaType: application/json
    notAlternative: true

params:
  alternate: Alternate
  subtitle: Subtitle
  description: Description
  statics: /
  # when your site url is like 'http://site.com/child', set root as '/child/'
  root: /
  since: 2022

  sidebar:
    avatar: avatar.jpg
    position: right

  fancybox: true

  widgets:
    random_posts: true
    recent_comments: true

  reward:
    enable: true
    account:
      wechatpay: wechatpay.jpg
      alipay: alipay.png
  
  social:
    github:
      icon: ic i-github
      link: https://github.com
    twitter:
      icon: ic i-twitter
      link: https://twitter.com

  algolia:
    appid: 
    apikey: 
    indexname: 
    hits: 10

  #publicCDN: https://cdn.jsdelivr.net/gh/birdgg/hugo-theme-shoka@gh-pages
  publicCDN: ""

  opengraph:
    twitter: 

  waline:
    serverURL: https://blog-comment-zeta-nine.vercel.app
    visitor: true   # 文章访问量统计
    pageview: true
    lang: zh-CN     # 语言，默认 zh-CN
    login: enable   # 登录模式状态，默认值 enable，force 可以强制登录
    wordLimit: 0    # 评论字数限制，0 为不限制，默认值为 0
    pageSize: 10    # 评论列表分页，数字为条数，默认值 10
    highlight: true # 代码高亮，默认 true
    meta: ['nick', 'mail', 'link'] # 评论者相关属性，默认 ['nick', 'mail', 'link']
    requiredMeta: ['nick', 'mail'] #设置评论者属性必填项，默认 []（即匿名）
    placeholder: ヽ(○´∀`)ﾉ♪
    copyright: true # 是否显示页脚版权信息
    emoji: [
      'https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/bilibili',
    ]
